services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mosquitto/conf:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/logs:/mosquitto/log:rw
    restart: unless-stopped

  energy_meter:
    build: ./
    image: tuya-energy-meter
    restart: unless-stopped
    network_mode: host